<a href="https://colab.research.google.com/github/wenshanliu653/Udemy_DS_bootcamp/blob/main/section-02/introduction_to_numpy_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
#資料型態
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.0, 3.3], #
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a2.shape

(2, 3)

In [10]:
a1.shape

(3,)

In [11]:
a3.shape

(2, 3, 3)

In [13]:
a1.size,a2.size,a3.size


(3, 6, 18)

In [19]:
#用panda df 去裝NumPy Arrary
import pandas as pd
df =pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [22]:
#Creating array
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype #資料型態

dtype('int64')

In [24]:
type(sample_array) #整個array type

numpy.ndarray

In [25]:
zeros = np.zeros((2, 3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array = np.arange(10) #限定一個range 產出10 element 的 array

In [28]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
range_array = np.arange(0, 20, 2) #限定一個range 產出0~20 間隔為2的array
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
random_array = np.random.randint(0, 10, size=(3, 5)) #random 產出3*5 的array, 數值在0~10 內
random_array

array([[2, 4, 6, 2, 6],
       [2, 5, 2, 9, 8],
       [4, 8, 6, 7, 4]])

In [39]:
random_array.shape

(3, 5)

In [41]:
random_array.size

15

In [74]:
random_array_2 = np.random.random((5, 3))  #random create a 5row 3 columns artray
#每次生成都會不一樣
random_array_2

array([[0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677],
       [0.43860151, 0.98837384, 0.10204481],
       [0.20887676, 0.16130952, 0.65310833],
       [0.2532916 , 0.46631077, 0.24442559]])

In [54]:
random_array_2.shape

(5, 3)

In [57]:
random_array_3 = np.random.rand(5,3) #只要一個括號
random_array_3

array([[0.71424001, 0.16644147, 0.04497066],
       [0.70528854, 0.64117409, 0.89759121],
       [0.47054955, 0.54665127, 0.64513687],
       [0.12518585, 0.73437641, 0.17322089],
       [0.93854684, 0.10898643, 0.81646386]])

In [79]:
# Pseudo-random numbers
np.random.seed(seed=0) #當設定seed 時 每次執行就會都一樣了
random_array_4 = np.random.randint(6, size=(3, 3))
random_array_4

array([[4, 5, 0],
       [3, 3, 3],
       [1, 3, 5]])

In [66]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [63]:
np.random.seed(seed=0)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [78]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

#3. Viewing Arrays and Matrixs


In [80]:
#uniqe 值
np.unique(random_array_4)

array([0, 1, 3, 4, 5])

In [81]:
a1

array([1, 2, 3])

In [84]:
ones=np.ones((3)) #全都是1
ones

array([1., 1., 1.])

In [85]:
# array 運算
a1 + ones

array([2., 3., 4.])

In [86]:
a1 - ones

array([0., 1., 2.])

In [87]:
a1*ones

array([1., 2., 3.])

In [89]:
a1/ones

array([1., 2., 3.])

In [91]:
a1

array([1, 2, 3])

In [90]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [92]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [103]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [98]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [104]:
a2*a3   #會報錯
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [106]:
a1 / ones

array([1., 2., 3.])

In [107]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [109]:
a2//a1 #兩個//就是除號 ＋round 小數點

array([[1., 1., 1.],
       [4., 2., 2.]])

In [112]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [113]:
a2 **2 #次方

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [118]:
np.square(a2) #平方

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [120]:
np.add(a1, ones)

array([2., 3., 4.])

In [122]:
a1 % 2

array([1, 0, 1])

In [124]:
a1 % 2

array([1, 0, 1])

In [126]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [127]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])