<a href="https://colab.research.google.com/github/wenshanliu653/Udemy_DS_bootcamp/blob/main/section-02/introduction-to-numpy-video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
#資料型態
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.0, 3.3], #
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a2.shape

(2, 3)

In [10]:
a1.shape

(3,)

In [11]:
a3.shape

(2, 3, 3)

In [13]:
a1.size,a2.size,a3.size


(3, 6, 18)

In [19]:
#用panda df 去裝NumPy Arrary
import pandas as pd
df =pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [ ]:
#Creating array